tap "homebrew/bundle"
tap "dagger/homebrew-tap"

brew "azure-cli"
brew "bash"
brew "git"
brew "git-lfs"
brew "graphviz"
brew "jenv"
brew "eza"
brew "fzf"
brew "bat"
brew "starship"
brew "zoxide"
brew "neovim"
brew "kubernetes-cli"
brew "go"
brew "node"
brew "ansible"
brew "fd"
brew "ripgrep"
brew "dagger"


cask "1password"
cask "1password-cli"
cask "font-hack-nerd-font"
cask "ghostty"
cask "jetbrains-toolbox"
cask "orbstack"
cask "temurin@21"
cask "keepassxc"
cask "raycast"
cask "obsidian"
cask "spotify"
